name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master

            - name: Setup Node.js 12.x
              uses: actions/setup-node@master
              with:
                node-version: 12.x
                registry-url: 'https://registry.npmjs.org'

            - name: Install Dependencies
              run: yarn

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@master
              with:
                # build the packages and call changeset publish
                publish: yarn release
              env:
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                # See comment about issue 'project's .npmrc not respected #58'
                #     https://github.com/changesets/action/issues/58#issuecomment-728353474
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                # This token is provided by Actions, you do not need to create your own token
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
